[project]
name = "pynq_pattern"
version = "0.1.0"

[build]
source = "src"
target = { type = "directory", path = "target" }
clock_type = "posedge"
reset_type = "sync_high"
omit_project_prefix = true
implicit_parameter_types = ["string"]
expand_inside_operation = true
